### ISSUE TITLE
wordpress开启后登录提示致命错误。

### ISSUE THREAD

**Issue by NyaDoo** [Tencent-Cloud-Plugins/tencentcloud-wordpress-plugin-captcha#8]
Fatal error: Uncaught Error: Call to undefined method TencentCloud\Common\Exception\TencentCloudSDKException::getErrorCode() in /www/wwwroot/NyaDoo_Main/wp-content/plugins/tencentcloud-captcha/TencentCloudCaptchaActions.php:538 Stack trace: #0 /www/wwwroot/NyaDoo_Main/wp-content/plugins/tencentcloud-captcha/TencentCloudCaptchaActions.php(349): TencentCloudCaptchaActions::verifyCodeReal() #1 /www/wwwroot/NyaDoo_Main/wp-includes/class-wp-hook.php(292): TencentCloudCaptchaActions->tencent_wordpress_capthca_loginCodeVerify() #2 /www/wwwroot/NyaDoo_Main/wp-includes/plugin.php(212): WP_Hook->apply_filters() #3 /www/wwwroot/NyaDoo_Main/wp-includes/pluggable.php(582): apply_filters() #4 /www/wwwroot/NyaDoo_Main/wp-includes/user.php(95): wp_authenticate() #5 /www/wwwroot/NyaDoo_Main/wp-login.php(1128): wp_signon() #6 {main} thrown in /www/wwwroot/NyaDoo_Main/wp-content/plugins/tencentcloud-captcha/TencentCloudCaptchaActions.php on line 538

**Comment by jerryzwu** [comment]
使用php7.3或php7.4
