### ISSUE TITLE
wordpress 验证后登录提示致命错误，php版本7.3，wordpress版本5.4.6/5.7.2，请问该如何解决呢？

### ISSUE THREAD

**Issue by eeshuibuxing** [Tencent-Cloud-Plugins/tencentcloud-wordpress-plugin-captcha#9]
Fatal error: Uncaught Error: Call to undefined method TencentCloud\Common\Exception\TencentCloudSDKException::getErrorCode() in /volume1/web/wordpress/wp-content/plugins/tencentcloud-captcha/TencentCloudCaptchaActions.php:538 Stack trace: #0 /volume1/web/wordpress/wp-content/plugins/tencentcloud-captcha/TencentCloudCaptchaActions.php(492): TencentCloudCaptchaActions::verifyCodeReal('t03ui2v0Tpt9tmx...', '@p2g', '2025285025', '0GpcB8fDaxg6KYw...') #1 /volume1/web/wordpress/wp-includes/class-wp-hook.php(287): TencentCloudCaptchaActions->tencent_wordpress_captcha_commentCodeVerify(Array) #2 /volume1/web/wordpress/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #3 /volume1/web/wordpress/wp-includes/comment.php(2098): apply_filters('preprocess_comm...', Array) #4 /volume1/web/wordpress/wp-includes/comment.php(3395): wp_new_comment(Array, true) #5 /volume1/web/wordpress/wp-comments-post.php(25): wp_handle_comment_submission(Array) #6 {main} thrown in /volume1/web/wordpress/wp-content/plugins/tencentcloud-captcha/TencentCloudCaptchaActions.php on line 538
您的站点遇到了致命错误。

**Comment by xiaoxianggongzi** [comment]
没人开发了吗？？我也遇到这个问题了

**Comment by eeshuibuxing** [comment]
解决了，需要领取免费包或者购买套餐包
